### ISSUE TITLE
PB Resets Slider Settings for Some Domains

### ISSUE THREAD

**Issue by ldbapp** [EFForg/privacybadgerfirefox#492] opened 2015-08-12 13:10 UTC
On some, but not all domains, PB will reset my slider settings.  For example if I slide it to red to block a domain, the refresh the page, PB will again show that domain's slider as green.

Example shown in https://youtu.be/6HajgkCe74k

Desired outcome: slider settings are kept where they are set.

**Comment by cooperq** [comment] 2015-08-12 20:48
duplicate of #458

**Comment by ldbapp** [comment] 2015-08-13 02:35
I read through #458 and my issue doesn't seem like anything discussed there.  Is there some internal reason why this is a duplicate?  I don't see it.  

I can set sliders to red for most domains, but for some the setting doesn't "stick".

**Comment by cooperq** [comment] 2015-08-13 05:12
Sorry, I think I was confused. Can you give me exact steps to reproduce the problem? And can you tell me if you have any non standard privacy or security settings in firefox? Can you also please tell me what version of the browser you have.

**Comment by ldbapp** [comment] 2015-08-15 03:05
Here are the steps I use to reproduce the problem.  Though I don't know if you'll be able to reproduce this exactly, given the vagaries of what content gets sent to whom for each webpage.  

- Go to https://support.mozilla.org/en-US/products/firefox/protect-your-privacy
- I see a domain www.surveygizmo.com listed under "the following domains don't appear to be tracking you".  
- Set it to be blocked.  
- Click outside the PB menu to refresh the page.  
- Look at PB again and the slider is back to green for that domain.

This is for one website, but it happens to me on many others.  The video link I posted earlier shows some page on huffingtonpost.com.  In that video, the offending domains were listed as ones that were tracking me.

Since this doesn't happen for all domains and all websites, I'm not sure what's causing PB to misbehave on some domains and not others.  I don't know enough about how websites or PB work to give a more definitive set of steps to reproduce.  

Here are some more examples.  On cnn.com the error didn't happen.  On spectrum.ieee.org the error happened with domain api-v3.tinypass.com.  On slashdot.org the error didn't happen.  On www.swingingcafedoors.com, the error happened for all domains from olark.com (there were a bunch of them including api.olark.com and log.olark.com).

I have lots of non-standard privacy and security settings.  I've toggled many of the values mentioned on these pages
https://support.mozilla.org/en-US/kb/how-stop-firefox-making-automatic-connections
https://support.mozilla.org/en-US/kb/how-do-i-turn-do-not-track-feature
https://support.mozilla.org/en-US/kb/settings-privacy-browsing-history-do-not-track.  

I use a custom hosts file to block domains I don't like (redirect to localhost).

I do *not* have Firefox's tracking protection turned on (but I'm going to turn it on as I just discovered it):  https://support.mozilla.org/en-US/kb/tracking-protection-firefox.  I do *not* use any third-party ad blockers.

I'm using Firefox 40.0.

HTH!  Feel free to ask for more info.

**Comment by SwartzCr** [comment] 2015-08-19 20:42
Not sure if it's related but I noticed today that contentPolicy is using ._isPreloadedWhitelistRequest rather than  _heuristicCookieblocksRequest to see if something needs shouldn't be blocked
This seems wrong, but maybe calling _heuristicCookieblocksRequest is redundant because we're checking isUserYellowlist? just going to leave this here in case it's useful

**Comment by butrus** [comment] 2015-08-20 16:20
Hi!
I'm the reporter of #529, I have the Debian brand of Firefox (named Iceweasel), version 38.2.0esr-1~deb7u1.
I have NoScript 2.6.9.35rc2, AdBlock Plus 2.6.0 and a couple of other Addons installed. Also I have a number of tweak configurations of firefox...

**Comment by cooperq** [comment] 2015-09-14 20:31
Are you still having this issue? I am unable to reproduce it.

**Closed by cooperq** 2015-09-14 20:31 UTC
Labels: bug
