### ISSUE TITLE
Make option to disable counter

### ISSUE THREAD

**Issue by ericschultz** [EFForg/privacybadgerfirefox#277] opened 2015-01-21 02:01 UTC
Privacy Badger has been causing a strange problem in my Firefox menu. This occurs in Firefox Beta, version 36 and in Firefox Developer Edition, version 37.  On most pages, the menu will quickly open and then disappear. On the next open, most of the menu is empty. I've attached a screen shot to illustrate this.

This only happens if the Privacy Badger button is in the Firefox menu; if it's not in the menu, the menu works fine. I tried debugging using the Firefox debugger but I don't fully understand the process for handling buttons in Firefox addons. I'm happy to debug or assist with some direction on this bug.

For reference, I'm running on Windows 8.1 64-bit.
![Firefox Menu mostly missing](https://cloud.githubusercontent.com/assets/94169/5829972/11344d20-a0df-11e4-9d7f-e698b950daab.png)

**Comment by cooperq** [comment] 2015-02-09 22:22
Interesting, I will have to test this.

**Comment by NJC2** [comment] 2015-02-28 02:52
I just experienced this problem after Firefox updated to 36 today.  It wasn't fun figuring out which addon was causing it by disabling them one at a time.  Next time I have to do that, maybe I'll start from the bottom and work up.

**Comment by cooperq** [comment] 2015-03-02 21:14
Confirmed, I have reproduced this. I will hunt down this bug ASAP.

**Comment by arcum** [comment] 2015-03-16 11:41
Hmz - it's not a bug in privacybadger, it's Firefox. Please make a setting to disable the counter on your icon. That's what is causing the menu to *crash* - it's a bug in Firefox, I have the same problem with other addons, but they give an option to turn the counter on/off, off = problem solved.

**Comment by cooperq** [comment] 2015-03-24 07:07
@arcum thanks for the tip, I will re-open this issue and make an option

**Comment by cooperq** [comment] 2015-03-24 07:10
@arcum do you have a link to the relevant issue in bugzilla?

**Comment by jamesgecko** [comment] 2015-03-24 08:00
I can reproduce this on both OS X and Windows with Privacy Badger and µBlock. Can't find [anything canonical-ish in Bugzilla in the past four months](https://bugzilla.mozilla.org/buglist.cgi?bug_status=__open__&comments=0&content=menu&product=Firefox&query_format=specific&limit=0), though. Here are issues that look related, but nobody appears to have figured out that the issue is extension icons that have counters on them.

- https://bugzilla.mozilla.org/show_bug.cgi?id=1140823
- https://bugzilla.mozilla.org/show_bug.cgi?id=1136394 (See attached video)
- https://bugzilla.mozilla.org/show_bug.cgi?id=1124663

Maaaaybe related? (It's about the menu failing to display after an update tour)

- https://bugzilla.mozilla.org/show_bug.cgi?id=949663

**Comment by arcum** [comment] 2015-03-24 08:12
@jamesgecko yeah haven't found anything specific either... I'll fix a bugreport on bugzilla.

**Comment by arcum** [comment] 2015-03-24 08:30
Et voila - reported at -> https://bugzilla.mozilla.org/show_bug.cgi?id=1146808

**Comment by arcum** [comment] 2015-03-25 09:10
Marked as duplicate of this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1029937

**Comment by cooperq** [comment] 2015-04-29 22:42
This is now an option as of 0.2.6 and the counter is off by default.

**Closed by cooperq** 2015-04-29 22:42 UTC
Labels: bug, urgent
