### ISSUE TITLE
Firefox 41 blocks Privacy Badger(unsigned add-on)

### ISSUE THREAD

**Issue by Dylan-G** [EFForg/privacybadgerfirefox#527] opened 2015-08-18 19:21 UTC
In Firefox 41, Mozilla started blocking unverified extensions(https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox). Because Privacy Badger is not signed by Mozilla, Firefox has automatically disabled the extension and prevents installing unsigned extensions, thus disabling Privacy Badger and preventing the extension to be installed/enabled.

FF: 41.0b1
PB: 1.0.1
OS: Windows 10

**Comment by cooperq** [comment] 2015-08-18 19:26
Please look through the issues before submitting a new one. 
This is a duplicate of #358

**Closed by cooperq** 2015-08-18 19:26 UTC
