### ISSUE TITLE
Extraneous scrollbar in UI on Firefox on Linux

### ISSUE THREAD

**Issue by jdhoek** [EFForg/privacybadgerfirefox#464] opened 2015-08-07 08:00 UTC
In Firefox Badger's UI is being broken with a vertical scrollbar in an area that looks like it should never gain any scrollbars:

![badger_misaligned](https://cloud.githubusercontent.com/assets/683699/9131367/21ff2352-3ceb-11e5-8ff4-c913c526180d.png)

This is causing the weird and sloppy scrolling behaviour seen on this screenshot.

I suspect some elements turn out to be higher (fonts?) for this combination of browser and OS than in other environments, triggering the browser to render a scrollbar for the taller-than-expected pane.

* Firefox 39.0
* Ubuntu Linux 14.10 (Unity)
* Privacy Badger 1.0.0

**Comment by nekromoff** [comment] 2015-08-07 08:48
duplicate of #457

**Comment by SwartzCr** [comment] 2015-08-07 22:22
yup this happens when the first run indicator has't been removed by looking through the first run comic.
Additionally it might have to do with your screen resolution, can you tell em what your screen resolution is?

**Comment by nyuszika7h** [comment] 2015-08-07 22:24
1600x900 for me.

**Comment by nekromoff** [comment] 2015-08-07 23:17
1920x1080
i don't think it's related to the screen resolution.

**Comment by jdhoek** [comment] 2015-08-08 09:53
@SwartzCr 
1920×1080.

I did flip through the first run comic on one machine, didn't on another. Both have this problem; the link to that comic at the top of the Badger's menu doesn't seem to be the cause of this bug; it happens with and without it.

I suspect that the **The following domains don't appear to be tracking you** line is rendered wider than expected causing the line to break. This can happen with the different font rendering engines on Linux, Mac, and Windows. Is it supposed to sit on one line?

**Closed** 2015-08-13 22:24 UTC
Labels: ui

**Comment by cooperq** [comment] 2015-08-15 02:47
This should be fixed by the newest version 1.0.1, please update your addons and try again.

**Comment by jdhoek** [comment] 2015-08-20 08:06
@cooperq 

Great, that fixes the scrollbar issue for me. There is still some related layout funkiness with the "The following domains […]" line, but I will open a separate issue for that.
