### ISSUE TITLE
Blocks camo.githubusercontent.com

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/privacybadgerfirefox#483] opened 2015-08-10 20:29 UTC
This breaks images, such as Privacy Badger's build status.

**Comment by SwartzCr** [comment] 2015-08-20 07:56
githubusercontent is on the cookie block list so I'd say this is a duplicate of #516
I'm going to close this in favor of that, please feel free to continue to comment there

**Closed by SwartzCr** 2015-08-20 07:56 UTC
Labels: site-bug
