### ISSUE TITLE
Uninstalling and re-installing privacybadger does not clear tracker cache

### ISSUE THREAD

**Issue by Hainish** [EFForg/privacybadgerfirefox#430] opened 2015-07-23 16:46 UTC
To reproduce:

1. Go to a few sites, build up your tracker blocking cache
2. Uninstall the extension
3. Reinstall the extension
4. Go to site that has blocked trackers (they're still blocked!)

There should be a way to clear the privacybadger cache.

This issue does not occur in the Chrome extension.

**Comment by cooperq** [comment] 2015-07-23 17:59
This is kinda a duplicate of #10, there was a button to clear the cache but it was in a menu that I removed. I should add it back to the options page.

**Comment by Hainish** [comment] 2015-07-23 18:38
Perhaps a desirable solution to this is to clear the cache upon
installation? Or is persistence a desired property? Either way, it should
behave consistently across FF/Chrome.

**Comment by cooperq** [comment] 2015-07-23 21:13
putting your comments in #10 so we don't duplicate.

**Closed** 2015-07-23 21:16 UTC
Labels: duplicate
