### ISSUE TITLE
Priacy Badger reset itself

### ISSUE THREAD

**Issue by Garve** [EFForg/privacybadgerfirefox#533] opened 2015-08-20 13:06 UTC
Hi!

A few minutes ago, PB reset itself. Since there is no button for doing so (I read that it will be added again,  but I still use a version without that button), I think this is a serious bug. There were around 1200 potential trackers in my list when I last checked it. Now it's 20 again. Does anyone know why this happened? 

Using PB version 1.0.1 from addons.mozilla.org, 
Firefox 40.0.2,
Fedora 22,
I didn't delete anything in my profile directory.

**Comment by cooperq** [comment] 2015-08-20 23:02
Did anything happen before this? Did you change any settings or did firefox get updated or anything?

**Comment by Garve** [comment] 2015-08-20 23:20
No, nothing of this. I can't even reproduce it, because I didn't know what could have caused this. It didn't even occurred after a restart of the browser, I just noticed that on some website there was advertising, which has not been there before. I checked the sliders and everything was green again. In the Option Menu, all the 1200+ potential tracking domains were gone. So essentially somehow I found a secret reset button.

Good thing is, that privacy Badger learns fast. After browsing for less than one hour, he learned everything again, without me doing anything. Thumbs up for this great addon by the way! 

Sorry that I can't give any instructions how to reproduce it. Also no other addon got updated and I also didn't do any system upgrades. Just surfing and suddenly wondering what happened there. Is it a problem, that the list of potential tracking domains was too long? How long is yours at the moment?

**Comment by jimfr** [comment] 2015-08-21 14:51
I've seen the same thing.  Also, all my whitelisted domains were erased.   Starting over...   Like Garve, I didn't notice anything happening, just went to look at whitelisted domains and noticed that it was empty; I had about 10 domains there.

**Comment by jawz101** [comment] 2015-09-22 15:09
That pisses me off.  I had over 2000 potentials on my list and now 5.  I have no idea what changed but it defeats the purpose of the whole app.

**Comment by cooperq** [comment] 2015-09-22 19:11
Wow, this seems really bad. @jawz101 have you recently changed any settings in firefox that may have caused this? Can you try to reproduce it? (I will also try to reproduce it.)

**Comment by jawz101** [comment] 2015-09-22 20:47
Sorry for the aggressiveness.  I will try to reproduce, though!
I get a vibe it's something to do with seeing those 2 versions and maybe something Firefox Sync-ish, Windows and Linux... who knows.

**Comment by jawz101** [comment] 2015-09-22 20:52
... actually, I just reproduced.
Had 1.0.1 from Mozilla's AMO site with 103 potential trackers counted jid1-MnnxcxisBPnSXQ@jetpack.xpi
then installed 1.0.2 from EFF jid1-MnnxcxisBPnSXQ-eff@jetpack.xpi

under FFox addon page it shows both listed, I restarted FFox and both remain listed and the tracker count is back at 2 potential trackers collected.

**Comment by jawz101** [comment] 2015-09-22 21:07
Also, one preference to consider, if I recall, is if a 3rd party site hosts an add-on if you append the url of the 3rd party site to this preceded by a comma it acknowledges updates from a 3rd party.  Though, with the package names being different I don't think it would work regardless.  May want to reach out to Giorgio Maone but I don't think he uses this setting.  He does host his NoScript addon on both addons.mozilla.org and development versions on noscript.net and informaction.com
addons.trustedSourceHostnames

**Comment by cypherpunk** [comment] 2015-09-23 10:58
@jawz101 
- I tried to manually update PB from 1.0.1 to 1.0.2 (due to #620) since Firefox didn't notify me about any available updates. I also ended up with two entries in the Add-ons list. My PB settings weren't reset though. Not sure why your settings were reset.
- I uninstalled the newly installed 1.0.2 because I didn't want to lose my settings. I'll wait for a proper update that Firefox can detect as an update.

@cooperq 
Any plans to release 1.0.2 and later versions in such a manner that Firefox recognizes them as updates to the existing installed PB add-on?

**Comment by cooperq** [comment] 2015-09-23 20:33
Where did you install 1.0.1 and 1.0.2 from? The versions on AMO and EFF have different extension ids (but the same code). This is due to a mozilla signing requirement. If you have 1.0.1 from eff.org it should automatically update to 1.0.2 no problem, if it doens't then I might have messed up the update scripts (but I'm pretty sure I checked and people were updating fine.)

Either way I don't think this is the cause of the issue that is described in this bug, since it started 5 days  before I relased 1.0.2

**Comment by Garve** [comment] 2015-09-23 20:55
It has been 1 months for me, so maybe I don't remember everything so well anymore. But I can't remember that I upgraded anything. I was just surfing, checked the trackers (were around 1200), continued surfing, noticed advertising, checked again, 5 knows trackers. I don't think, that I did anything obvious there, that could have caused this. Maybe there is a bug very well hidden somewhere.

**Comment by cypherpunk** [comment] 2015-09-24 00:49
@cooperq 
I don't remember where 1.0.1 came from. 1.0.2 came from EFF since the mozilla version was still showing as 1.0.1 when i tried.

**Comment by cypherpunk** [comment] 2015-09-24 18:13
@cooperq 
I found the files `jid1-MnnxcxisBPnSXQ@jetpack.xpi` and `jid1-MnnxcxisBPnSXQ-eff@jetpack.xpi` in `%APPDATA%\Roaming\Mozilla\Firefox\Profiles\********.default\extensions`. From the dates, I determined that my PB 1.0.1 came from addons.mozilla.org. The EFF version is the installation I described above (I must have disabled 1.0.2 rather than uninstall as I reported).

The addons.mozilla.org version hasn't been updated. - it is still listed as 1.0.1. Any plans to update this in sync with the EFF version?

**Comment by cooperq** [comment] 2015-10-02 20:27
Yes in the future it will be in sync. The only difference between 1.0.1 and 1.0.2 is the id (I had to increase the version to get the eff.org version signed by mozilla).
I suspect that this whole problem is due to updates and id changes. I am going to close this bug for now and we can re-open it if people continue running into this problem.

**Closed by cooperq** 2015-10-02 20:27 UTC
Labels: bug
