### ISSUE TITLE
FF36.0 - Moving PB icon to menu will cause menu to disappear when opened

### ISSUE THREAD

**Issue by thrnz** [EFForg/privacybadgerfirefox#312] opened 2015-03-01 22:00 UTC
In FireFox 36.0, when the PrivacyBadger icon has been moved to the menu, the menu will disappear almost immediately after being opened. Clicking the menu button a second time will then only show the bottom most menu buttons. Moving the icon back to the toolbar returns the menu behaviour to normal. I have noticed this behaviour on three separate machines.

**Comment by cooperq** [comment] 2015-03-03 01:37
duplicate of #277

**Closed by cooperq** 2015-03-03 01:37 UTC
