### ISSUE TITLE
PB constantly "loading"

### ISSUE THREAD

**Issue by AdamBullen** [EFForg/privacybadgerfirefox#324] opened 2015-03-23 00:39 UTC
Nothing is working I just get the "loading" indication.

I have APB; HTTPS everywhere; No Script and Lastpass addons intalled.

Last pass wont auto fill forms now; requires me to go to the menu and tell the site to auto fill.

UPDATE: disabling the No Script add-on fixes the "loading" issue. I will try browsing with No Script disabled for now.

**Comment by pguth** [comment] 2015-03-23 03:00
I have that problem too running Ubuntu/[Firefox Developer](http://www.mozilla.org/firefox/aurora/?utm_source=firefox-affiliates&utm_medium=banner&utm_campaign=aff-desktop-download-aurora).

**Comment by AdamBullen** [comment] 2015-03-23 03:03
I am running on windows firefox V36.04; I will try it on Ubuntu when I get home from work. 

All seems to be working with no script disabled from the add-on manager.

**Comment by AdamBullen** [comment] 2015-03-23 20:01
I tried the PB software on Firefox for Ubuntu; I was stuck at the loading point again, I have no other add-ons installed.

OS: Ubuntu 14.04
FF: V36.01

**Comment by titanous** [comment] 2015-03-23 22:58
Duplicate of #303.

**Comment by AdamBullen** [comment] 2015-03-23 23:02
Duplicate issue see above.

**Closed** 2015-03-23 23:01 UTC
