### ISSUE TITLE
PB tracker settings switched from red to green

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#322] opened 2015-03-18 18:31 UTC
After closing a browser window (firefox 36.0.1), a browser window that I had not opened, displaying a site I had not visted (hotels.com), appeared behind it.  Trackers from the following sites would automatically reset to "green" after I set them to "red". marketing...ensighten.com   ;   marketing.activate.ensighten.com  ;   nexus.ensighten.com   ;  mpp.vindicosuite.com  ;   and  survey.122.2o7.net

**Comment by cooperq** [comment] 2015-03-27 00:58
Seems like a duplicate of #319

**Closed** 2015-03-27 00:58 UTC
Labels: duplicate
