### ISSUE TITLE
PB not working on FF Aurora 38

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#308] opened 2015-02-28 00:41 UTC
I've been using FF on the aurora update channel for some months with PB, with no problems up to version 37. But with the last aurora update to version 38 PB stopped working, only showing the "loading" on it's interface.

<a href="http://imgur.com/rMbCQ8e"><img src="http://i.imgur.com/rMbCQ8e.jpg" title="source: imgur.com" /></a>

Thanks for this great extension. I doesn't even feel the need to use adblock anymore.

**Comment by titanous** [comment] 2015-02-28 04:43
Dupe of #303.

**Comment by cooperq** [comment] 2015-03-02 21:18
Agreed, please follow  up in #303

**Closed by cooperq** 2015-03-02 21:18 UTC
Labels: duplicate
