### ISSUE TITLE
Nightly has prevented this site from installing an unverified add-on

### ISSUE THREAD

**Issue by scottstensland** [EFForg/privacybadgerfirefox#474] opened 2015-08-08 03:09 UTC
Is it possible to override Mozilla Nightly 42.0a1 (2015-08-07) from blocking install from your

       https://www.eff.org/privacybadger

**Comment by rugk** [comment] 2015-08-08 10:35
duplicate of https://github.com/EFForg/privacybadgerfirefox/issues/358

**Comment by nyuszika7h** [comment] 2015-08-08 10:45
For the time being at least, you can set `xpinstall.signatures.required` to `false`.

**Comment by SwartzCr** [comment] 2015-08-10 16:42
unfortunately the signing queue for firefox is a long involved process. We're working with AMO to get this signed, but until then you won't be able to install it in 42 (though maybe you are able to turn of signatures in about:config)
we hope to have a signed version soon to alleviate this problem

**Closed** 2015-08-11 19:50 UTC
Labels: duplicate
