### ISSUE TITLE
Cannot right click in 'broken site reporter'

### ISSUE THREAD

**Issue by rugk** [EFForg/privacybadgerfirefox#537] opened 2015-08-20 17:37 UTC
In the part of Privacy Pager where you can submit a broken website you cannot right click. Not even in the text box!

This way you can't e.g.:
* change your spell checking language
* copy and paste with the context menu

**Comment by SwartzCr** [comment] 2015-08-20 18:13
you may also notice that you can't right click at all on the privacy badger pop-up
I'm going to guess that this is mozilla intended behavior, and possibly something you can 'fix' by editing your about:config
I'm asking in irc.mozilla.org #jetpack and if I get back a response that this is our fault I'll re-open this issue but for now I'm going to close it

**Comment by SwartzCr** [comment] 2015-08-20 18:28
okay it seems that this is because xul pages don't have context menus by default, so we need to add the appropriate attributes to it to be able to have right clicks.
some information is here: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/menupopup
I'm going to re-open and mark this as a good volunteer task (maybe @taravancil wants to do more work with the pop-up?)

**Comment by cooperq** [comment] 2015-08-20 20:08
I'm pretty sure we would have to write some XUL hooks to make this work, and I am *extremely* reluctant to introduce any XUL into our codebase, I think it will make maintainance even more difficult than it currently is.  I think this is a super low priority.

**Comment by rugk** [comment] 2015-08-21 16:13
Mozilla is going to depreciate XUL in the future, so implementing this like this is not a good idea IMO.
Maybe the new WebExtensions could help more in this case.

https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/

**Comment by cooperq** [comment] 2015-08-24 23:38
I'm closing this. We definitely don't want to add any XUL to our codebase.

**Closed by cooperq** 2015-08-24 23:38 UTC
Labels: wontfix
