### ISSUE TITLE
0.2.4+ causes zoom settings to be forgotten

### ISSUE THREAD

**Issue by pix64** [EFForg/privacybadgerfirefox#268] opened 2015-01-05 06:15 UTC
Using 0.2.4 or 0.2.5, per domain zoom settings are forgotten.

1. Go to google.com
2. Zoom out
3. Close tab
4. Go back to google.com
5. Site is zoomed back to default

**Comment by pix64** [comment] 2015-01-05 06:35
Now sure what was triggering this. Problem occurred immediately installation of 0.2.5. Removed Privacy Badger issue was no longer present. Installed again, issue was present again. Tested under clean profile and could not reproduce issue. Disabled extensions on main profile, issue was no longer present. Re-enabled extensions, issue still no longer present.

**Comment by cooperq** [comment] 2015-02-09 22:03
I am unable to reproduce the issue. Perhaps it was a conflict with another extension. I am going to close this issue for now.

**Closed by cooperq** 2015-02-09 22:03 UTC
