### ISSUE TITLE
Settings for website keep going back to what they were before I changed them!

### ISSUE THREAD

**Issue by nunayerbeezwacks** [EFForg/privacybadgerfirefox#290] opened 2015-01-31 06:00 UTC
I keep changing settings for trackers for websites from green and yellow to red, but when I go back to a website that I changed them for, they go back to what they were before. This is particularly disturbing because most of these trackers are for Facebook, Google, and Twitter, the trackers I am most concerned about. Looks like I have to go back to using DNTM.

**Comment by cooperq** [comment] 2015-02-11 21:58
Have you changed any of the privacy settings in firefox from the defaults? What version of privacy badger and firefox are you using. Do you have any other extensions installed?  Can you tell me which websites this is happening on?

**Comment by Jasonp15** [comment] 2015-03-18 03:35
I am also having a problem with the settings automatically resetting to green right after I change them to red. I change the sliders to red, the page refreshes, and all of the sliders are Green again. It happens on Yahoo!, Facebook, Google, and YouTube. It's especially annoying because I recognize some of the trackers as potential problems. I don't know what version of Privacy badger I am using, I downloaded and installed it on 3/16/15, so whatever version was the latest on that day. I am using Firefox and I have the AdBlock extension installed.

**Comment by cooperq** [comment] 2015-05-19 03:44
duplicate of #319

**Closed by cooperq** 2015-05-19 03:44 UTC
