### ISSUE TITLE
Travis CI log output fails to load with Privacy Badger

### ISSUE THREAD

**Issue by jsha** [EFForg/privacybadgerfirefox#495] opened 2015-08-12 21:57 UTC
With Privacy Badger Firefox enabled, if I visit a Travis CI build page (e.g. https://travis-ci.org/EFForg/https-everywhere/builds/75347801), the log output never loads. However, deactivating Privacy Badger on that page allows it to work.

**Comment by cooperq** [comment] 2015-08-13 22:00
Duplicate of #482

**Closed by cooperq** 2015-08-13 22:00 UTC
Labels: duplicate
