### ISSUE TITLE
Deactivate button not clickable

### ISSUE THREAD

**Issue by xur86x** [EFForg/privacybadgerfirefox#320] opened 2015-03-16 16:43 UTC
It just happened to me that the button to deactivate Privacy Badger was not clickable. Restarting Firefox solved the problem.

**Comment by SwartzCr** [comment] 2015-04-21 00:13
Did you get a dialogue saying that privacy badger had crashed?
The next time this happens please try to see if there is info in your browser's console and attach it.
I'm going to close this ticket, but please open a new one if this happens again and you have more information into the root cause

**Closed by SwartzCr** 2015-04-21 00:13 UTC

**Comment by xur86x** [comment] 2015-04-21 10:04
Will do. Since a simple restart solved it, I suspect there was a conflict when updating it to a more recent version. There was no dialogue.
