### ISSUE TITLE
Had to disable it because it kept whitelisting cookies domains I had manually blacklisted

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#383] opened 2015-06-19 09:17 UTC
I have an extremely restrictive cookie policy.  Global block, with a very short manual whitelist.  (Currently 12 domains allowed for session, one of which is my OpenWRT router running Luci.)  I also have CS lite so I can temporarily enable cookies if I want to use a site that needs cookies for some specific thing (e.g. actually buying something, as opposed to browsing).

Anyway, I was checking my cookies the other say and noticed a cookie from youtube.  WTF?  How did that get there?  www.youtube.com and i.imgur.com were listed as first-party only.  Not only did I not do that, I don't even know how to create such an entry in the list.  (I only know how to do block, allow for session, and permit.)

So I deleted the unwanted cookies (*all* cookies from google's empire are forbidden *always*, no exceptions) and changed the entries to explicit block.

But I kept checking.  Just one visit to the site didn't make that entry reappear, but after browsing for a bit, boom!  My explicit blocks had gotten changed.

I admit I freaked out for a bit.  I thought that youtube had figured out a back door in Firefox to enable its cookies, and spent a while chasing down that theory.  Then I remembered I'd installed Privacy Badger last week and tried disabling that.

Problem solved.

Why the *hell* is Privacy Badger overriding my cookies settings with more permissive ones?

**Comment by cooperq** [comment] 2015-06-19 17:52
Duplicate of #206, we are working on it.

**Closed by cooperq** 2015-06-19 17:52 UTC
