### ISSUE TITLE
Using the sliders is super slow (in Settings)

### ISSUE THREAD

**Issue by skunkcruncher** [EFForg/privacybadgerfirefox#653] opened 2015-10-18 15:09 UTC
and unresponsive.  I've been trying to block the 455 trackers badger detected, I've been able to edit 5 in the last 10 minutes.  Super slow to respond, and then once you've edited one site to be blocked, it doesn't respond to the next item until 15~ or so seconds after.

**Comment by cypherpunk** [comment] 2015-10-23 23:03
Same here. Every part of the interface is like this for me. Modifying the whitelist? Good luck with that. I had to stop using the extension because of this. It's way beyond unbearable when doing multiple things in the interface.

**Comment by cooperq** [comment] 2015-11-03 01:12
duplicate of #643

**Closed by cooperq** 2015-11-03 01:12 UTC
