### ISSUE TITLE
drop down menu shows settings relative to its former activation during 2 sec when activated

### ISSUE THREAD

**Issue by antistress** [EFForg/privacybadgerfirefox#442] opened 2015-07-26 09:08 UTC
Hi,

Using Privacy Badger 0.99 on my Dell Mini 9 / Inspiron 910 netbook (32 bits Intel Atom N270 CPU & 8,9" WSVGA 1024*600 screen) shows 2 things :
1) PB drop down menu works well on that screen despite its small vertical resolution, thanks to scrollbars, which is great :)
2) There is a lag when I open the drop down menu by clicking onto the Badger icon : it first shows the settings of the former site where I had activated it before, and then, after 1.5 or 2 sec it refreshes the settings to show theses related to current site.
This leads to bad user experience and subjective feeling that PB is not reliable nor strong enough

Thanks

**Comment by cooperq** [comment] 2015-07-27 18:25
Thanks for the comment on 1, 2 is a duplicate of #432  which we are working on!

**Closed** 2015-07-27 18:53 UTC
Labels: duplicate
