### ISSUE TITLE
Request: do not allow exeption automatically in Firefox' s cookie accepted list

### ISSUE THREAD

**Issue by geplus** [EFForg/privacybadgerfirefox#206] opened 2014-08-26 10:17 UTC
Hi, 
I notice thatPrivacyBager adds websites in the Firefox's cookies whitelist, for example from www.paypal.com and wikimedia.org, withouth any advice, and these exeptions remain for each session of Firefox, even if I use the Private browsing mode.
I want that these exeption were removed when you close Firefox.

**Comment by DavidStaron** [comment] 2015-03-04 11:00
I just noticed the same thing.. took me ages to test/find what extension was causing it, very annoying.

> I want that these exeption were removed when you close Firefox.

In my opinion the cookie exceptions should not be added at all.

For example this makes the [Self Destructing Cookies extension](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/) useless because now suddenly everyone who uses this addon has allowed cookie exceptions for Google, Youtube, etc.

**Comment by geplus** [comment] 2015-03-08 11:06
Yeah David, I agree with you: these exeptions should not be added at all, definitely: It's an high privacy related issue.

**Comment by cooperq** [comment] 2015-03-27 00:49
this is caused by the same things as #103 and #238 and #167 which is namely that privacy badger handles the cookie block list by adding things to the internal firefox list of cookie exceptions. The real fix here is to refactor privacy badger so that it doesn't add domains to the cookie exceptions list in order to block them.

**Comment by cooperq** [comment] 2015-07-23 03:03
This will be fixed by #425 as will the other bugs related to this.

**Closed** 2015-07-23 22:42 UTC
Labels: bug, high-priority
