### ISSUE TITLE
Does not show trackers on the current page in FF48

### ISSUE THREAD

**Issue by yumashka** [EFForg/privacybadgerfirefox#792] opened 2016-08-03 12:46 UTC
After updating to Firefox 48:
- When entering any page Privacy Bager shows icon with non-zero counter indicating that it has blocked some trackers. It really does according to how pages are looking (almost no ads)
- But after clicking on icon it shows no trackers and says that it "detected 0 potential trackers on this page" however counter is still non-zero

Tested on two old installations and one fresh FF+PB installation

![pb-counter](https://cloud.githubusercontent.com/assets/15315151/17365951/c4132686-5999-11e6-8147-93778f4bbb77.png)

**Comment by onderzoekspraktijk** [comment] 2016-08-04 12:06
+1

**Comment by haesemeyer** [comment] 2016-08-04 14:11
Exactly same issue here after update to FF48 (Mac OSX). In fact, the usual sliders briefly flash up after clicking on the toolbar icon and then vanish changing to a screen as in the screenshot above.

**Comment by jbwCode** [comment] 2016-08-05 17:43
I also have experienced this issue with symptoms as described by the original poster, yumashka.  I have been using Privacy Badger for months on several systems and it has been working just fine, 

But since upgrading to Firefox 48 on my Windows 10 Pro x64 PC this issue has started.

I have tried starting Firefox 48 with a clean test profile including Privacy Badger as the only extension. No improvement shown.

I tested with Xubuntu 16.04 x64 VM running Firefox 47.  No issues with Privacy Badger.  So I upgraded it to Firefox 48, and then the issue started.

I tested on a windows XP x86 VM running Firefox 30-something, and Privacy Badger was fine. So I upgraded to Firefox 48, and same issue started again.

So it is my conclusion that something has changed in Firefox 48 for multiple platforms, that is now breaking Privacy Badger.

**Comment by oneofthedamons** [comment] 2016-08-06 05:34
+1 for Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by chekavy** [comment] 2016-08-06 09:34
The same issue in Firefox 48 on Fedora 24.

**Comment by squaregoldfish** [comment] 2016-08-06 21:33
I have slightly different behaviour to @haesemeyer - I don't see the trackers, but I briefly see a 'Loading...' message which then disappears.

(Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0)

**Comment by sathood** [comment] 2016-08-07 14:04
same problem encountered for the last few days.

noted something else, PB isn't picking up any new trackers.  

so, it appears to be blocking existing trackers that have been limited/blocked, but ability to control newly encountered trackers has been disabled  ; (

**Comment by markrrr** [comment] 2016-08-08 00:06
same problem in FF48 under Linux Mint 17.3

**Comment by X-dark** [comment] 2016-08-08 13:49
This will probably be fixed by EFForg/privacybadgerchrome#845

**Comment by b1teman** [comment] 2016-08-08 15:53
This will probably be fixed by EFForg/privacybadgerchrome#845
Will this fix Firefox V48? Also dose EFF know about this issue?

**Comment by cooperq** [comment] 2016-08-08 20:24
EFF Developer here.
For all of you I need to know, do you have multiprocess firefox (E10S) Enabled?  You can check in settings. If you do, does privacy badger work again if you disable multiprocess firefox?

**Comment by haesemeyer** [comment] 2016-08-08 20:29
Multiprocess windows (as shown by about:support) is disabled on my firefox.

**Comment by cooperq** [comment] 2016-08-08 21:00
okay this was apparently not a multiprocess problem. I found the fix for this and I will release a new version today.

**Comment by b1teman** [comment] 2016-08-08 21:02
I use FF v48 looked for it when I typed about:supprt and found this. "Multiprocess Windows 	0/2 (Disabled)". I just saw you will release a new vertion today. How will I get that and how will I know I got it?

**Comment by cooperq** [comment] 2016-08-08 21:05
@b1teman it will auto update. You will know you got it because privacy badger will work again!

**Comment by cooperq** [comment] 2016-08-08 21:05
the fixed version will be 1.8.0

**Comment by b1teman** [comment] 2016-08-08 21:07
I use FF v48 looked for it when I typed about:supprt and found this. "Multiprocess Windows 	0/2 (Disabled)". I just saw you will release a new vertion today. How will I get that and how will I know I got it?

**Comment by b1teman** [comment] 2016-08-08 21:08
The update will come thru the update function in my Add-ons Manager section in FF v48?

**Comment by cooperq** [comment] 2016-08-08 22:32
Correct. 

On August 8, 2016 2:08:57 PM PDT, b1teman <notifications@github.com> wrote:
>The update will come thru the update function in my Add-ons Manager
>section in FF v48?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/privacybadgerfirefox/issues/792#issuecomment-238378129

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by b1teman** [comment] 2016-08-09 13:22
Thanks I downloaded the new version this morning from your site. It would not update thru FF Add-ons page. Is that something that will happen for all the other FF users? 

Thank you for the quick update. So far it is working the way it use to. So Thanks again.

**Comment by haesemeyer** [comment] 2016-08-09 13:53
For me it updates just fine through firefox and the problems seem to be fixed!

Thanks for the quick action.

**Comment by oneofthedamons** [comment] 2016-08-09 14:12
Confirmed fixed for my Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0 – thanks :-)

**Comment by neonriots** [comment] 2016-08-09 15:11
Woohoo, PB works again.  Thanks, devs.  = )

**Comment by jramnani** [comment] 2016-08-09 17:32
If you're impatient and don't want to wait for Firefox's Auto Update to kick in, you can turn off Automatic Updates in the Privacy Badger preferences, and a "Check for Update" button will appear.  You can click that to get an update sooner.  Just don't forget to re-enable Auto Updates when you're done.

Confirmed version 1.8.0 works for me.

Firefox 48.0
OS X 10.11.6

**Comment by jbwCode** [comment] 2016-08-09 19:35
All good here again with PB version 1.8.0.  Thanks for the quick fix!!!

Used the Firefox "Check for Updates" command in the Add-ons manager tools drop-down.

Firefox 48.0
Windows 10 Pro version 1511, OS Build 10586.494

**Comment by yumashka** [comment] 2016-08-09 20:08
I also confirmed version 1.8.0 works for me: Firefox 48.0 / Win7x64

**Comment by yumashka** [comment] 2016-08-09 20:18
Oops! Sorry, close issue too fast. Need to reopen it.
Not all UI elements are shown correctly:
![pb180](https://cloud.githubusercontent.com/assets/15315151/17532069/e1c7c7a4-5e8f-11e6-9a18-47112ef06605.jpg)

**Comment by cooperq** [comment] 2016-08-09 23:28
That is a separate issue, please open a new issue.

**Closed by cooperq** 2016-08-09 23:28 UTC
