### ISSUE TITLE
No way to clear cookie list? 

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#665] opened 2015-11-03 15:42 UTC
There is currently no way to reset privacy badger's blocked cookie list so the app essentially contains a permanent history log. This bug is a privacy issue.

**Comment by cooperq** [comment] 2015-11-05 21:13
duplicate of #10 
see there for more thoughts on this.

**Closed by cooperq** 2015-11-05 21:13 UTC
