### ISSUE TITLE
1.0.3 Privacy Badger

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#667] opened 2015-11-04 11:41 UTC
FF 43 does not allow privacy badger.

**Comment by rugk** [comment] 2015-11-04 18:39
duplicate of https://github.com/EFForg/privacybadgerfirefox/issues/656

**Comment by cooperq** [comment] 2015-11-04 20:28
Please explain what you mean when you say it does not allow privacy badger.

**Closed** 2015-11-07 00:45 UTC
