### ISSUE TITLE
Is it possible to reset Privacy Badger customizations back to default?

### ISSUE THREAD

**Issue by MHWallace** [EFForg/privacybadgerfirefox#601] opened 2015-09-10 06:47 UTC
I periodically like to reset extensions that I have adjusted settings on, back to their default settings. I have set various domains to be allowed, over-riding PB settings from what they were out-of-the-box. (I understand that it begins by allowing all and "learns" what to block based on my browsing behavior...) I want to reset these back to their default state, removing any customizations I have made. I could go through the PB Options > Filter Settings panel, but there are presently 769 potential tracking domains listed. That's time-prohibitive and I don't know enough about each to do that manually and know I've done it "right".

I have searched using both DuckDuckGo and Google and I can't find any helpful information on how to do this with Privacy Badger. There is no indication that this is possible in the FAQs at https://www.eff.org/privacybadger. I've also looked at the GitHub repository (here) and have so far not found anything relevant to my question. There is no indication that what I am trying to do is possible. If it is possible then it seems to be undocumented on the public list of FAQs.

**Comment by Garve** [comment] 2015-09-11 22:25
Hi!

There was a reset button once, but it was removed. But as far as I know, it will probably be added again in future versions. I am also missing this feature.

**Comment by cooperq** [comment] 2015-09-14 19:32
See #10  we used to have a clear storage button. I removed it but I guess it will need to be re-added.

**Comment by MHWallace** [comment] 2015-09-15 03:02
I vote for adding a clear data button into PB Options. As a user I would like to be able to reset back to settings that PB has when first installed. (clear PBadger's local stores and reset cookie permissions set by PBadger.) Not knowing the inner workings of PB I'm not sure exactly what is possible but my idea is to reset to settings as they were "out of the box".

**Comment by cooperq** [comment] 2015-09-16 01:44
closing this as a duplicate of #10

**Closed by cooperq** 2015-09-16 01:44 UTC
Labels: duplicate
