### ISSUE TITLE
The last slide of the "first run" screen has a typo

### ISSUE THREAD

**Issue by danielquinn** [EFForg/privacybadgerfirefox#718] opened 2016-01-11 13:17 UTC
The image in slide number 16 says:

> Thank you for taking an important, easy step toward protecting **you** privacy!

**Comment by mlopezfm** [comment] 2016-01-14 18:41
the issue is with "/data/icons/slideshow/PB-layouts-15.png"
submitting PR issue718 to correct

**Comment by cooperq** [comment] 2016-02-06 00:06
fixed by @mlopezfm !

**Closed by cooperq** 2016-02-06 00:06 UTC
